/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import org.junit.jupiter.api.Test;

import chess.modell.Board;
import chess.modell.Piece;
import chess.viewController.Chess;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Map;
import java.util.TreeMap;

class ChessTest {

}
